// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPdrDANqmh4ZET96rWSZTibkLWXZtFQU',
    appId: '1:523553823091:web:fb8c7bbe98425117c9cd06',
    messagingSenderId: '523553823091',
    projectId: 'tunijobs-7823f',
    authDomain: 'tunijobs-7823f.firebaseapp.com',
    storageBucket: 'tunijobs-7823f.firebasestorage.app',
    measurementId: 'G-FK5LGQXR1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxv-s4NNe8vUNWxSUoqrFLP3XkYQVKgU',
    appId: '1:523553823091:android:7c33fe815323642fc9cd06',
    messagingSenderId: '523553823091',
    projectId: 'tunijobs-7823f',
    storageBucket: 'tunijobs-7823f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5MhLh6pcC5kgXwdMv_ck8YNQjyZjFVo',
    appId: '1:523553823091:ios:08c28c9c7fe34f5bc9cd06',
    messagingSenderId: '523553823091',
    projectId: 'tunijobs-7823f',
    storageBucket: 'tunijobs-7823f.firebasestorage.app',
    iosBundleId: 'com.tunijobs.tunijobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5MhLh6pcC5kgXwdMv_ck8YNQjyZjFVo',
    appId: '1:523553823091:ios:08c28c9c7fe34f5bc9cd06',
    messagingSenderId: '523553823091',
    projectId: 'tunijobs-7823f',
    storageBucket: 'tunijobs-7823f.firebasestorage.app',
    iosBundleId: 'com.tunijobs.tunijobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQPdrDANqmh4ZET96rWSZTibkLWXZtFQU',
    appId: '1:523553823091:web:beee8ab539f98307c9cd06',
    messagingSenderId: '523553823091',
    projectId: 'tunijobs-7823f',
    authDomain: 'tunijobs-7823f.firebaseapp.com',
    storageBucket: 'tunijobs-7823f.firebasestorage.app',
    measurementId: 'G-YY4NJHSSQK',
  );

}